title: Site

pages:
  template:
    - home
    - projects

files:
  fields:
    caption:
      label:
        en: Caption
        bg: Надпис
      type: textarea

fields:
  title:
    label:
      en: Title
      bg: Заглавие
    type: text

  logo:
    label:
      en: Logo
      bg: Лого
    type: image