title: Site

pages:
  template:
    - home
    - projects
    - gallery
    - about
    - contacts

files:
  fields:
    caption:
      label:
        en: Caption
        bg: Надпис
      type: textarea

fields:
  title:
    label:
      en: Title
      bg: Заглавие
    type: text

  slogan:
    label:
      en: Slogan
      bg: Мото
    type: text

  logo:
    label:
      en: Logo
      bg: Лого
    type: image